name: A test workflow
on: push
jobs:
  setup-config:
    name: Prepare for deployment
    runs-on: ubuntu-latest

    outputs:
      argocd_app_name:  ${{ steps.argocd_setup.outputs.argocd_app_name }}

    env:
      GREETING: drb-test-434
    steps:
      - name: argocd steup
        id: argocd_steup
        shell: bash
        run: |
          echo ::set-output name=argocd_app_name::core-services-pr${{ github.event.pull_request.number }}
      - uses: hmarr/debug-action@v2

  deploy-pr:
    env:
      ARGOCD_APP_NAME: ${{ needs.setup-config.outputs.argocd_app_name }}
    runs-on: ubuntu-latest
    name: PR Deployment
    needs: [setup-config]
    steps:
      - uses: hmarr/debug-action@v2    


