name: A test workflow
on: push
jobs:

  setup-config:
    name: setup config
    runs-on: ubuntu-latest

    outputs:
      argocd_app_name: ${{ steps.argocd_setup.outputs.argocd_app_name }}
    env:
      GREETING: drb-test-434
    steps:
      - name: argocd steup
        id: argocd_setup
        shell: bash
        run: |
          echo ::set-output name=argocd_app_name::id-${{ github.push_id }}

  debug:
    name: debug
    needs: [setup-config]
    runs-on: ubuntu-latest
    steps:
    - name: debug print
      env:
        ARGOCD_APP_NAME: ${{ needs.setup-config.outputs.argocd_app_name }}
      run: |
        echo "ARGOCD_APP_NAME: $ARGOCD_APP_NAME"
      shell: bash

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."

