name: A test workflow
on: push
jobs:

  setup-config:
    name: setup config
    runs-on: ubuntu-latest

    outputs:
      argocd_app_name: ${{ steps.argocd_setup.outputs.argocd_app_name }}
    env:
      GREETING: drb-test-434
    steps:
      - name: argocd steup
        id: argocd_steup
        shell: bash
        run: |
          echo ::set-output name=argocd_app_name::pr${{ github.event.pull_request.number }}

  debug:
    name: debug
    needs: [setup-config]
    runs-on: ubuntu-latest
    steps:
    - name: Clean up ArgoCD deployments
      env:
        ARGOCD_APP_NAME: ${{ needs.setup-config.outputs.argocd_app_name }}
      run: |
        echo "ARGOCD_APP_NAME: $ARGOCD_APP_NAME"
      shell: bash

