name: A test workflow
on: push
jobs:
  get-config:
    name: Prepare for deployment
    runs-on: ubuntu-latest

    outputs:
      argocd_app_name:  ${{ steps.argocd_setup.outputs.argocd_app_name }}

    steps:
      - name: argocd steup
        id: argocd_steup
        shell: bash
        run: |
          echo ::set-output name=argocd_app_name::core-services-pr${{ github.event.pull_request.number }}
      - uses: hmarr/debug-action@v2

    


